# Generated by Django 5.0.2 on 2024-02-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Наживка',
                'verbose_name_plural': 'Наживка',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='fish',
            options={'ordering': ['id'], 'verbose_name': 'Рыбы', 'verbose_name_plural': 'Рыбы'},
        ),
    ]
